### ISSUE TITLE
"use_frameworks!" line in ios Podfile results in a build break when deploying to iOS for Firebase codelab

### ISSUE THREAD

**Issue by jwmcglynn** [flutter/friendlychat#2]
Line in question: [ios/Podfile:9](https://github.com/flutter/friendlychat/blob/09f574012f6b878ef3df433541e3af7f2b087ebd/ios/Podfile#L9)

The Firebase for Flutter Codelab uses [this repository](https://codelabs.developers.google.com/codelabs/flutter-firebase/#2) as the base for the project, but due to the presence of "use_frameworks!" the compile fails with the following error:

`[!] The 'Pods-Runner' target has transitive dependencies that include static binaries: ...`

In the [firebase/firebase #9694](https://github.com/flutter/flutter/issues/9694#issuecomment-303474620) issue the codelab was supposedly updated for this issue, but this git repository was not, so it still reproed for me.

To fix this issue, I simply removed that line.

**Comment by eseidelGoogle** [comment]
FYI @collinjackson

**Comment by collinjackson** [comment]
The Firebase codelab points to the flutter/friendlychat-steps repo in two places and the flutter/friendlychat in one place. I think we should have one canonical place for the codelab steps. I proposed a change to point everything to flutter/friendlychat-steps. @LarkAscending can you please review it?

Once that change is pushed, the flutter/friendlychat repo can be deprecated.

**Comment by LarkAscending** [comment]
Thanks! The codelab change LGTM. We did this for the I/O-bound version for <valid reason at the time> but it always bugged me.
https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#2

I also replaced the link to the obsolete friendlychat-flutter repo, which redirected to friendlychat-steps. Less mysterious, and that redirect doesn't have to be maintained.

**Comment by collinjackson** [comment]
Thanks. Marking this closed and moving the repo private.
